name: shopper_mobile
description: Shopper ERP / POS mobile shell (barcode scanning, bn/en UI).
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  mobile_scanner: ^5.2.3

flutter:
  uses-material-design: true
